# Generated by Django 2.1.4 on 2019-01-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BirthdayTrackersite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('rock', models.CharField(max_length=50)),
                ('chanceDay', models.CharField(max_length=50)),
            ],
        ),
    ]
