# Generated by Django 2.1.4 on 2019-01-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BirthdayTrackersite', '0002_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='months',
            name='planet',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
